seed: 42
gpu: 0
save_dir: coco_experiments
save_name: coco_exp2
overwrite: ~

# transformer added 1

# model
model:
  clip: ViT-B/32
  bert: dbmdz/bert-base-turkish-cased
  max_length: 35

# optimizer
lr: 5e-4
lr_proj: 5e-4
betas: [0.9, 0.99]
weight_decay: 0.01

num_workers: 8
batch_size: 64
max_iter: 100000
warm_up_iter: 10000
num_eval_iter: 8000
target_metric: 'Bleu_4' # Bleu_1 Bleu_2 Bleu_3 Bleu_4 METEOR ROUGE_L CIDEr SPICE

# dataset
train_dataset_name: coco-karphaty
train_dataset_root: "Data/coco/"
train_json_path: "Data/coco/annotations/coco_karpathy_train_tr.json"


test_dataset_name: coco-karphaty
test_dataset_root: "Data/coco/"
val_json_path: "Data/coco/annotations/coco_karpathy_val_gt_tr.json"

