
seed: 42
gpu: 0
save_dir: tasviret_experiments_new
save_name: tasviret_exp1_base16
overwrite: ~

# transformer added 1

# model
model:
  clip: ViT-B/16
  bert: dbmdz/bert-base-turkish-cased
  max_length: 35
  proj: True
  proj_num_head: 16

# optimizer
lr: 5e-4
lr_proj: 5e-4
betas: [0.9, 0.99]
weight_decay: 0.01

num_workers: 8
batch_size: 64
max_iter: 50000
warm_up_iter: 10000
num_eval_iter: 8000
target_metric: 'Bleu_4' # Bleu_1 Bleu_2 Bleu_3 Bleu_4 METEOR ROUGE_L CIDEr

# dataset
train_dataset_name: tasvir-et
train_dataset_root: "Data/flickr/flickr30k-images"
train_json_path: "Data/tasvir-et/tasvir_train.json"


test_dataset_name: tasvir-et
test_dataset_root: "Data/flickr/flickr30k-images"
val_json_path: "Data/tasvir-et/tasvir_val.json"


